#pragma once

#define ORE_MOUSE_BUTTON_1         0
#define ORE_MOUSE_BUTTON_2         1
#define ORE_MOUSE_BUTTON_3         2
#define ORE_MOUSE_BUTTON_4         3
#define ORE_MOUSE_BUTTON_5         4
#define ORE_MOUSE_BUTTON_6         5
#define ORE_MOUSE_BUTTON_7         6
#define ORE_MOUSE_BUTTON_8         7
#define ORE_MOUSE_BUTTON_LAST      ORE_MOUSE_BUTTON_8
#define ORE_MOUSE_BUTTON_LEFT      ORE_MOUSE_BUTTON_1
#define ORE_MOUSE_BUTTON_RIGHT     ORE_MOUSE_BUTTON_2
#define ORE_MOUSE_BUTTON_MIDDLE    ORE_MOUSE_BUTTON_3